// This file is automatically generated by Next.js to include types for Next.js features. 
// It is recommended not to modify this file directly.

/// <reference types="next" />
/// <reference types="next/types/global" />